import { heroSlider1, heroSlider2, heroSlider3 } from "../assets";
import { facebook, instargram } from "../assets";
import { service1, service2, service3, service4 } from "../assets";
import { jewellerySliderImage } from "../assets";
import {
  jewelleryRing1,
  jewelleryRing2,
  jewelleryRing3,
  jewelleryRing4,
  jewelleryRing5,
  jewelleryRing6,
  jewelleryRing7,
  jewelleryRing8,
  jewelleryRing9,
  jewelleryRing10,
  jewelleryRing11,
  jewelleryRing12,
  jewelleryRing13,
  jewelleryRing14,
  jewelleryRing15,
  jewelleryRing16,
  jewelleryRing17,
  jewelleryRing18,
  jewelleryRing19,
  jewelleryRing20,
  jewelleryRing21,
  jewelleryRing22,
  jewelleryRing23,
  jewelleryRing24,
  jewelleryRing25,
  jewelleryRing26,
  jewelleryRing27,
  jewelleryRing28,
  jewelleryRing29,
  jewelleryRing30,
  jewelleryRing31,
  jewelleryRing32,
  jewelleryRing33,
  jewelleryRing34,
  jewelleryRing35,
  jewelleryRing36,
  jewelleryRing37,
} from "../assets";

import {
  jewelleryBracelet1,
  jewelleryBracelet2,
  jewelleryBracelet3,
  jewelleryBracelet4,
  jewelleryBracelet5,
  jewelleryBracelet6,
  jewelleryBracelet7,
  jewelleryBracelet8,
  jewelleryBracelet9,
  jewelleryBracelet10,
  jewelleryBracelet11,
  jewelleryBracelet12,
  jewelleryBracelet13,
  jewelleryBracelet14,
  jewelleryBracelet15,
  jewelleryBracelet16,
  jewelleryBracelet17,
  jewelleryBracelet18,
  jewelleryBracelet19,
  jewelleryBracelet20,
  jewelleryBracelet21,
  jewelleryBracelet22,
  jewelleryBracelet23,
  jewelleryBracelet24,
  jewelleryBracelet25,
} from "../assets";

import {
  jewelleryChain1,
  jewelleryChain2,
  jewelleryChain3,
  jewelleryChain4,
  jewelleryChain5,
  jewelleryChain6,
  jewelleryChain7,
  jewelleryChain8,
  jewelleryChain9,
  jewelleryChain10,
  jewelleryChain11,
  jewelleryChain12,
  jewelleryChain13,
  jewelleryChain14,
  jewelleryChain15,
  jewelleryChain16,
  jewelleryChain17,
} from "../assets";

import {
  jewelleryEarrings1,
  jewelleryEarrings2,
  jewelleryEarrings3,
  jewelleryEarrings4,
  jewelleryEarrings5,
  jewelleryEarrings6,
  jewelleryEarrings7,
} from "../assets";

// Links and other informations
const facebookLink = "https://www.facebook.com/";
const instargramLink = "https://www.instagram.com/";

const contactNumber = "075 706 0941";
const email = "client@gmail.com";
const address = "Ampara";

export const heroSlide = [
  {
    id: "slider 1",
    img: heroSlider1,
  },
  {
    id: "slider 2",
    img: heroSlider2,
  },
  {
    id: "slider 3",
    img: heroSlider3,
  },
];

export const socialMedia = [
  {
    id: "instagram",
    link: instargramLink,
    img: instargram,
  },
  {
    id: "facebook",
    link: facebookLink,
    img: facebook,
  },
];

export const services = [
  {
    id: "service1",
    img: service1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service2",
    img: service2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service3",
    img: service3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service4",
    img: service4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
];

export const contactDetails = [
  {
    id: "contact-type-1",
    type: "Mobile",
    detail: contactNumber,
  },
  {
    id: "contact-type-2",
    type: "E-Mail",
    detail: email,
  },
  {
    id: "contact-type-3",
    type: "Address",
    detail: address,
  },
];

export const items = [
  {
    id: "item-1",
    name: "Ring",
    img: [jewelleryRing1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2023-06-20",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-2",
    name: "Bracelet",
    img: [jewelleryBracelet1],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-4",
    name: "Ring",
    img: [jewelleryRing2],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: 75000,
    date: "2023-06-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-3",
    name: "Chain",
    img: [jewelleryChain1],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-5",
    name: "Ring",
    img: [jewelleryRing3],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2023-07-02",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-6",
    name: "Bracelet",
    img: [jewelleryBracelet2],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: 85000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-7",
    name: "Ring",
    img: [jewelleryRing4],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: 75000,
    date: "2023-07-10",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-8",
    name: "Chain",
    img: [jewelleryChain2],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-9",
    name: "Chain",
    img: [jewelleryChain3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 125000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-10",
    name: "Ring",
    img: [jewelleryRing5],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 95000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-05-20",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-53",
    name: "Bracelet",
    img: [jewelleryBracelet3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-54",
    name: "Bracelet",
    img: [jewelleryBracelet4],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-11",
    name: "Bracelet",
    img: [jewelleryBracelet5],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 88000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-12",
    name: "Ring",
    img: [jewelleryRing6],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2022-05-4",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-13",
    name: "Ring",
    img: [jewelleryRing7],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2022-04-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-14",
    name: "Ring",
    img: [jewelleryRing8],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2022-08-30",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-15",
    name: "Ring",
    img: [jewelleryRing9],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-10-12",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-16",
    name: "Ring",
    img: [jewelleryRing10],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-10-13",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-17",
    name: "Ring",
    img: [jewelleryRing11],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-09-23",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-18",
    name: "Ring",
    img: [jewelleryRing12],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2024-01-02",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-19",
    name: "Ring",
    img: [jewelleryRing13],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-09-07",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-20",
    name: "Ring",
    img: [jewelleryRing14],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2024-02-12",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-21",
    name: "Ring",
    img: [jewelleryRing15],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-30",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-22",
    name: "Ring",
    img: [jewelleryRing16],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-12-29",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },

  {
    id: "item-23",
    name: "Ring",
    img: [jewelleryRing17],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-10-19",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },

  {
    id: "item-24",
    name: "Ring",
    img: [jewelleryRing18],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-11-04",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-25",
    name: "Ring",
    img: [jewelleryRing19],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-27",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-26",
    name: "Ring",
    img: [jewelleryRing20],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-11-29",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-27",
    name: "Ring",
    img: [jewelleryRing21],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-08-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-28",
    name: "Ring",
    img: [jewelleryRing22],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-11-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-29",
    name: "Ring",
    img: [jewelleryRing23],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-09-03",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-30",
    name: "Ring",
    img: [jewelleryRing24],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-12-06",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-31",
    name: "Ring",
    img: [jewelleryRing25],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-09-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing26],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing27],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing28],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing29],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing30],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing31],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing32],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing33],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing34],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing35],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  }, {
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing36],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },{
    id: "item-32",
    name: "Ring",
    img: [jewelleryRing37],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: false,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-33",
    name: "Bracelet",
    img: [jewelleryBracelet6],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-34",
    name: "Bracelet",
    img: [jewelleryBracelet7],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 192000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-35",
    name: "Bracelet",
    img: [jewelleryBracelet8],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-36",
    name: "Bracelet",
    img: [jewelleryBracelet9],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-37",
    name: "Bracelet",
    img: [jewelleryBracelet10],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-38",
    name: "Bracelet",
    img: [jewelleryBracelet11],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-39",
    name: "Bracelet",
    img: [jewelleryBracelet12],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-40",
    name: "Silver Bracelet",
    img: [jewelleryBracelet13],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 14000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-41",
    name: "Bracelet",
    img: [jewelleryBracelet14],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-42",
    name: "Bracelet",
    img: [jewelleryBracelet15],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-43",
    name: "Bracelet",
    img: [jewelleryBracelet16],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-44",
    name: "Bracelet",
    img: [jewelleryBracelet17],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-45",
    name: "Bracelet",
    img: [jewelleryBracelet18],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-46",
    name: "Bracelet",
    img: [jewelleryBracelet19],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-47",
    name: "Bracelet",
    img: [jewelleryBracelet20],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-48",
    name: "Bracelet",
    img: [jewelleryBracelet21],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-49",
    name: "Bracelet",
    img: [jewelleryBracelet22],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-50",
    name: "Bracelet",
    img: [jewelleryBracelet23],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-51",
    name: "Bracelet",
    img: [jewelleryBracelet24],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-52",
    name: "Bracelet",
    img: [jewelleryBracelet25],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-57",
    name: "Chain",
    img: [jewelleryChain4],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-58",
    name: "Chain",
    img: [jewelleryChain5],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-59",
    name: "Chain",
    img: [jewelleryChain6],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-60",
    name: "Chain",
    img: [jewelleryChain7],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-61",
    name: "Chain",
    img: [jewelleryChain8],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-62",
    name: "Chain",
    img: [jewelleryChain9],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-63",
    name: "Chain",
    img: [jewelleryChain10],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-64",
    name: "Chain",
    img: [jewelleryChain11],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-65",
    name: "Chain",
    img: [jewelleryChain12],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-66",
    name: "Chain",
    img: [jewelleryChain13],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-67",
    name: "Chain",
    img: [jewelleryChain14],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-68",
    name: "Chain",
    img: [jewelleryChain15],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-69",
    name: "Chain",
    img: [jewelleryChain16],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-70",
    name: "Chain",
    img: [jewelleryChain17],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-86",
    name: "Earring",
    img: [jewelleryEarrings1],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-87",
    name: "Earring",
    img: [jewelleryEarrings2],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: false,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-88",
    name: "Earring",
    img: [jewelleryEarrings3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-89",
    name: "Earring",
    img: [jewelleryEarrings4],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: true,
    offerPrice: 5000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-90",
    name: "Earring",
    img: [jewelleryEarrings5],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-91",
    name: "Earring",
    img: [jewelleryEarrings6],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: true,
    offerPrice: 40000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-92",
    name: "Earring",
    img: [jewelleryEarrings7],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: true,
    offerPrice: 40000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
];

export const jewelerySliderAssets = [
  {
    id: "1",
    img: jewellerySliderImage,
  },
  {
    id: "2",
    img: jewellerySliderImage,
  },
  {
    id: "3",
    img: jewellerySliderImage,
  },
];
