import { heroSlider1, heroSlider2, heroSlider3 } from "../assets";
import { facebook, instargram } from "../assets";
import { service1, service2, service3, service4 } from "../assets";
import { ring, bracelet, chain } from "../assets";
import { sample1, sample2, sample3 } from "../assets";
import { jewellerySliderImage } from "../assets";
import {
  jewelleryRing1,
  jewelleryRing2,
  jewelleryRing3,
  jewelleryRing4,
  jewelleryRing5,
  jewelleryRing6,
  jewelleryRing7,
  jewelleryRing8,
  jewelleryRing9,
  jewelleryRing10,
  jewelleryRing11,
  jewelleryRing12,
  jewelleryRing13,
  jewelleryRing14,
  jewelleryRing15,
  jewelleryRing16,
  jewelleryRing17,
  jewelleryRing18,
  jewelleryRing19,
  jewelleryRing20,
  jewelleryRing21,
  jewelleryRing22,
  jewelleryRing23,
  jewelleryRing24,
  jewelleryRing25,
  jewelleryRing26,
} from "../assets";

import {
  jewelleryBracelet1,
  jewelleryBracelet2,
  jewelleryBracelet3,
  jewelleryBracelet4,
  jewelleryBracelet5,
  jewelleryBracelet6,
  jewelleryBracelet7,
  jewelleryBracelet8,
  jewelleryBracelet9,
  jewelleryBracelet10,
  jewelleryBracelet11,
  jewelleryBracelet12,
  jewelleryBracelet13,
  jewelleryBracelet14,
  jewelleryBracelet15,
  jewelleryBracelet16,
  jewelleryBracelet17,
  jewelleryBracelet18,
  jewelleryBracelet19,
  jewelleryBracelet20,
  jewelleryBracelet21,
  jewelleryBracelet22,
  jewelleryBracelet23,
  jewelleryBracelet24,
} from "../assets";

import {
  jewelleryChain1,
  jewelleryChain2,
  jewelleryChain3,
  jewelleryChain4,
  jewelleryChain5,
  jewelleryChain6,
  jewelleryChain7,
  jewelleryChain8,
  jewelleryChain9,
  jewelleryChain10,
  jewelleryChain11,
  jewelleryChain12,
  jewelleryChain13,
  jewelleryChain14,
  jewelleryChain15,
  jewelleryChain16,
  jewelleryChain17,
  jewelleryChain18,
  jewelleryChain19,
  jewelleryChain20,
  jewelleryChain21,
  jewelleryChain22,
  jewelleryChain23,
  jewelleryChain24,
  jewelleryChain25,
  jewelleryChain26,
  jewelleryChain27,
  jewelleryChain28,
  jewelleryChain29,
  jewelleryChain30,
} from "../assets";

import {
  jewelleryEarrings1,
  jewelleryEarrings2,
  jewelleryEarrings3,
  jewelleryEarrings4,
  jewelleryEarrings5,
  jewelleryEarrings6,
  jewelleryEarrings7,
  jewelleryEarrings8,
  jewelleryEarrings9,
  jewelleryEarrings10,
  jewelleryEarrings11,
  jewelleryEarrings12,
  jewelleryEarrings13,
  jewelleryEarrings14,
  jewelleryEarrings15,
  jewelleryEarrings16,
  jewelleryEarrings17,
  jewelleryEarrings18,
} from "../assets";

// Links and other informations
const facebookLink = "https://www.facebook.com/";
const instargramLink = "https://www.instagram.com/";

const contactNumber = "075 706 0941";
const email = "client@gmail.com";
const address = "Ampara";

export const heroSlide = [
  {
    id: "slider 1",
    img: heroSlider1,
  },
  {
    id: "slider 2",
    img: heroSlider2,
  },
  {
    id: "slider 3",
    img: heroSlider3,
  },
];

export const socialMedia = [
  {
    id: "instagram",
    link: instargramLink,
    img: instargram,
  },
  {
    id: "facebook",
    link: facebookLink,
    img: facebook,
  },
];

export const services = [
  {
    id: "service1",
    img: service1,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service2",
    img: service2,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service3",
    img: service3,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
  {
    id: "service4",
    img: service4,
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
  },
];

export const contactDetails = [
  {
    id: "contact-type-1",
    type: "Mobile",
    detail: contactNumber,
  },
  {
    id: "contact-type-2",
    type: "E-Mail",
    detail: email,
  },
  {
    id: "contact-type-3",
    type: "Address",
    detail: address,
  },
];

export const items = [
  {
    id: "item-1",
    name: "Ring",
    img: [jewelleryRing1, sample1, sample2, sample3],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2023-06-20",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-2",
    name: "Bracelet",
    img: [jewelleryBracelet12, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-4",
    name: "Golden Ring",
    img: [jewelleryRing2, ring, sample1, sample3],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: true,
    offerPrice: 75000,
    date: "2023-06-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-3",
    name: "Chain",
    img: [jewelleryChain1, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-5",
    name: "Diamond Ring",
    img: [jewelleryRing3, sample1, sample2, sample3],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2023-07-02",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-6",
    name: "Golden Bracelet",
    img: [jewelleryBracelet11, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: true,
    offerPrice: 85000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-7",
    name: "Silver Ring",
    img: [jewelleryRing4, ring, sample2, sample3],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 85000,
    isStock: true,
    hasOffer: true,
    offerPrice: 75000,
    date: "2023-07-10",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-8",
    name: "Gold Chain",
    img: [jewelleryChain17, chain, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-9",
    name: "Sapphire Chain",
    img: [chain, sample3, sample1, sample2],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 125000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-10",
    name: "Emerald Ring",
    img: [jewelleryRing5, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 95000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-05-20",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-11",
    name: "Pearl Bracelet",
    img: [jewelleryBracelet18, bracelet, sample1, sample2],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 88000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-12",
    name: "Ruby Ring",
    img: [jewelleryRing6, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2022-05-4",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-13",
    name: "Ruby Ring",
    img: [jewelleryRing7, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2022-04-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-14",
    name: "Ruby Ring",
    img: [jewelleryRing8, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2022-08-30",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-15",
    name: "Ruby Ring",
    img: [jewelleryRing9, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-10-12",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-16",
    name: "Ruby Ring",
    img: [jewelleryRing10, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-10-13",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-17",
    name: "Ruby Ring",
    img: [jewelleryRing11, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-09-23",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-18",
    name: "Ruby Ring",
    img: [jewelleryRing12, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2024-01-02",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-19",
    name: "Ruby Ring",
    img: [jewelleryRing13, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-09-07",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-20",
    name: "Ruby Ring",
    img: [jewelleryRing14, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2024-02-12",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-21",
    name: "Ruby Ring",
    img: [jewelleryRing15, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-07-30",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-22",
    name: "Ruby Ring",
    img: [jewelleryRing16, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-12-29",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },

  {
    id: "item-23",
    name: "Ruby Ring",
    img: [jewelleryRing17, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-10-19",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },

  {
    id: "item-24",
    name: "Ruby Ring",
    img: [jewelleryRing18, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-11-04",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-25",
    name: "Ruby Ring",
    img: [jewelleryRing19, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-07-27",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-26",
    name: "Ruby Ring",
    img: [jewelleryRing20, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-11-29",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-27",
    name: "Ruby Silver Ring",
    img: [jewelleryRing21, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-08-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-28",
    name: "Diamond Gold Ring",
    img: [jewelleryRing22, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-11-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-29",
    name: "Titanium Ring",
    img: [jewelleryRing23, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-09-03",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-30",
    name: "Gold 25K Ring",
    img: [jewelleryRing24, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-12-06",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-31",
    name: "Gold 22K Ring",
    img: [jewelleryRing25, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-09-25",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-32",
    name: "Gold 18K Ring",
    img: [jewelleryRing26, ring, sample2, sample1],
    type: "ring",
    carat: 18,
    weight: 45.04,
    price: 120000,
    isStock: true,
    hasOffer: true,
    offerPrice: 105000,
    date: "2023-07-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quibusdam distinctio itaque quisquam illo ipsa tempore, aperiam deserunt repellat laborum veritatis.",
  },
  {
    id: "item-33",
    name: "Bracelet",
    img: [jewelleryBracelet1, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-34",
    name: "Pearl Bracelet",
    img: [jewelleryBracelet2, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 192000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-35",
    name: "Bracelet",
    img: [jewelleryBracelet3, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-36",
    name: "Bracelet",
    img: [jewelleryBracelet4, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-37",
    name: "Bracelet",
    img: [jewelleryBracelet5, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-38",
    name: "Bracelet",
    img: [jewelleryBracelet6, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-39",
    name: "Bracelet",
    img: [jewelleryBracelet7, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-40",
    name: "Silver Bracelet",
    img: [jewelleryBracelet8, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 14000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-41",
    name: "Bracelet",
    img: [jewelleryBracelet9, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },

  {
    id: "item-42",
    name: "Bracelet",
    img: [jewelleryBracelet10, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-43",
    name: "Bracelet",
    img: [jewelleryBracelet11, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-44",
    name: "Bracelet",
    img: [jewelleryBracelet12, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-45",
    name: "Bracelet",
    img: [jewelleryBracelet13, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-46",
    name: "Bracelet",
    img: [jewelleryBracelet14, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-47",
    name: "Bracelet",
    img: [jewelleryBracelet15, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-48",
    name: "Bracelet",
    img: [jewelleryBracelet16, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-49",
    name: "Bracelet",
    img: [jewelleryBracelet17, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-50",
    name: "Bracelet",
    img: [jewelleryBracelet18, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-51",
    name: "Bracelet",
    img: [jewelleryBracelet19, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-52",
    name: "Bracelet",
    img: [jewelleryBracelet20, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-53",
    name: "Bracelet",
    img: [jewelleryBracelet21, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-54",
    name: "Bracelet",
    img: [jewelleryBracelet22, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-55",
    name: "Bracelet",
    img: [jewelleryBracelet23, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-56",
    name: "Bracelet",
    img: [jewelleryBracelet24, sample1, sample2, sample3],
    type: "bracelet",
    carat: 18,
    weight: 45.04,
    price: 154000,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-57",
    name: "Chain",
    img: [jewelleryChain2, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-58",
    name: "Chain",
    img: [jewelleryChain3, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-59",
    name: "Chain",
    img: [jewelleryChain4, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-60",
    name: "Chain",
    img: [jewelleryChain5, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-61",
    name: "Chain",
    img: [jewelleryChain6, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-62",
    name: "Chain",
    img: [jewelleryChain7, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-63",
    name: "Chain",
    img: [jewelleryChain8, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-64",
    name: "Chain",
    img: [jewelleryChain9, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-65",
    name: "Chain",
    img: [jewelleryChain10, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-66",
    name: "Chain",
    img: [jewelleryChain11, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-67",
    name: "Chain",
    img: [jewelleryChain12, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-68",
    name: "Chain",
    img: [jewelleryChain13, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-69",
    name: "Chain",
    img: [jewelleryChain14, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-70",
    name: "Chain",
    img: [jewelleryChain15, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-71",
    name: "Chain",
    img: [jewelleryChain16, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-72",
    name: "Chain",
    img: [jewelleryChain17, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-73",
    name: "Chain",
    img: [jewelleryChain18, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-74",
    name: "Chain",
    img: [jewelleryChain19, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-75",
    name: "Chain",
    img: [jewelleryChain20, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-76",
    name: "Chain",
    img: [jewelleryChain21, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-77",
    name: "Chain",
    img: [jewelleryChain22, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-78",
    name: "Chain",
    img: [jewelleryChain23, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-79",
    name: "Chain",
    img: [jewelleryChain24, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-80",
    name: "Chain",
    img: [jewelleryChain25, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-81",
    name: "Chain",
    img: [jewelleryChain26, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-82",
    name: "Chain",
    img: [jewelleryChain27, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-83",
    name: "Chain",
    img: [jewelleryChain28, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-84",
    name: "Chain",
    img: [jewelleryChain29, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-85",
    name: "Chain",
    img: [jewelleryChain30, sample1, sample2, sample3],
    type: "chain",
    carat: 18,
    weight: 45.04,
    price: 355000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
  {
    id: "item-86",
    name: "Earring",
    img: [jewelleryEarrings1, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-87",
    name: "Diamond Earring",
    img: [jewelleryEarrings2, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-88",
    name: "Gold Earring",
    img: [jewelleryEarrings3, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-89",
    name: "Earring",
    img: [jewelleryEarrings4, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-90",
    name: "Diamond Earring",
    img: [jewelleryEarrings5, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-91",
    name: "Gold Earring",
    img: [jewelleryEarrings6, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-92",
    name: "Earring",
    img: [jewelleryEarrings7, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-93",
    name: "Diamond Earring",
    img: [jewelleryEarrings8, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-94",
    name: "Gold Earring",
    img: [jewelleryEarrings9, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-95",
    name: "Earring",
    img: [jewelleryEarrings10, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-96",
    name: "Diamond Earring",
    img: [jewelleryEarrings11, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-97",
    name: "Gold Earring",
    img: [jewelleryEarrings12, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-98",
    name: "Earring",
    img: [jewelleryEarrings13, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-99",
    name: "Diamond Earring",
    img: [jewelleryEarrings14, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-100",
    name: "Gold Earring",
    img: [jewelleryEarrings15, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-101",
    name: "Earring",
    img: [jewelleryEarrings16, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-102",
    name: "Diamond Earring",
    img: [jewelleryEarrings17, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-103",
    name: "Gold Earring",
    img: [jewelleryEarrings18, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-104",
    name: "Earring",
    img: [jewelleryEarrings7, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-105",
    name: "Diamond Earring",
    img: [jewelleryEarrings1, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-106",
    name: "Gold Earring",
    img: [jewelleryEarrings3, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },{
    id: "item-107",
    name: "Earring",
    img: [jewelleryEarrings5, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 5699,
    isStock: true,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },  {
    id: "item-108",
    name: "Diamond Earring",
    img: [jewelleryEarrings14, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 566000,
    isStock: true,
    hasOffer: true,
    offerPrice: 499999,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  }, {
    id: "item-109",
    name: "Gold Earring",
    img: [jewelleryEarrings9, sample1, sample2, sample3],
    type: "earring",
    carat: 18,
    weight: 45.04,
    price: 45000,
    isStock: false,
    hasOffer: false,
    offerPrice: null,
    date: "2022-03-14",
    details:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eligendi libero quo tempora, eveniet eaque, dolor tempore enim beatae magnam magni doloremque facere illum voluptas unde?",
  },
];

export const jewelerySliderAssets = [
  {
    id: "1",
    img: jewellerySliderImage,
  },
  {
    id: "2",
    img: jewellerySliderImage,
  },
  {
    id: "3",
    img: jewellerySliderImage,
  },
];
